export default interface FoodTruck {
    locationId: number,
    applicant: string,
    facilityType: "Truck" | "Push Cart" | undefined,
    cnn: string,
    locationDescription: string,
    address: string,
    blockLot: string,
    block: string,
    lot: string,
    permit: string,
    status: "EXPIRED" | "APPROVED" | "SUSPENDED" | "REQUESTED",
    foodItems: string,
    x: number,
    y: number,
    latitude: number,
    longitude: number,
    schedule: string,
    daysHours: string | undefined,
    nOISent: string | undefined,
    approved: Date,
    received: string,
    priorPermit: number,
    expirationDate: Date,
    location: string,
    firePreventionDistricts: number,
    policeDistricts: number,
    supervisorDistricts: number,
    zipCodes: string,
    neighborhoods: number
}